name: greplog

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        submodules: recursive
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Test GCC
      run: arm-none-eabi-gcc --version
      
    - name: Build libopencm3
      working-directory: ${{github.workspace}}/src/libopencm3
      run: make

    - name: Build Test
      working-directory: ./
      run: make
